version: '3'
services:
  mongodb-service:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    network_mode: "host"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: