apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: osm-ingress
  annotations:
spec:
  rules:
  - host: osm.project
    http:
      paths:
      - path: /
        backend:
          serviceName: flask
          servicePort: 5000